/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}', './public/index.html'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        mono: [
          'JetBrains Mono',
          'SF Mono',
          'Menlo',
          'Consolas',
          'ui-monospace',
          'monospace',
        ],
      },
      colors: {
        page: 'var(--bg-page)',
        panel: 'var(--bg-panel)',
        sidebar: 'var(--bg-sidebar)',
        elev: 'var(--bg-elev)',
        'elev-2': 'var(--bg-elev-2)',
        hover: 'var(--bg-hover)',
        active: 'var(--bg-active)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-soft': 'var(--border-soft)',
        text: 'var(--text)',
        'text-2': 'var(--text-2)',
        muted: 'var(--muted)',
        'muted-2': 'var(--muted-2)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-bg': 'var(--accent-bg)',
        'accent-border': 'var(--accent-border)',
        warn: 'var(--warn)',
        danger: 'var(--danger)',
        'syn-key': 'var(--syn-key)',
        'syn-str': 'var(--syn-str)',
        'syn-num': 'var(--syn-num)',
        'syn-fn': 'var(--syn-fn)',
        'syn-com': 'var(--syn-com)',
        'syn-tag': 'var(--syn-tag)',
        'syn-prop': 'var(--syn-prop)',
        'icon-md': 'var(--icon-md)',
        'icon-json': 'var(--icon-json)',
        'icon-yaml': 'var(--icon-yaml)',
        'icon-sh': 'var(--icon-sh)',
        'icon-folder': 'var(--icon-folder)',
      },
      boxShadow: {
        ide1: 'var(--shadow-1)',
        ide2: 'var(--shadow-2)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
      keyframes: {
        cursor: { '0%, 49%': { opacity: '1' }, '50%, 100%': { opacity: '0' } },
        marching: { to: { strokeDashoffset: '-12' } },
        archpulse: {
          '0%, 100%': { opacity: '1' },
          '50%, 70%': { opacity: '0.55' },
        },
      },
      animation: {
        cursor: 'cursor 1s steps(2) infinite',
        marching: 'marching 1.2s linear infinite',
        archpulse: 'archpulse 2.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
